### ISSUE TITLE
kata v1.11.0

### ISSUE THREAD

**Issue by ssst0n3** [ssst0n3/docker_archive#35]
```
time="2023-05-04T09:03:05Z" level=error msg="CPU property not found" arch=amd64 description=SSE4.1 na
me=sse4_1 pid=2251 source=runtime type=flag
time="2023-05-04T09:03:05Z" level=error msg="ERROR: System is not capable of running Kata Containers"
 arch=amd64 name=kata-runtime pid=2251 source=runtime
ERROR: System is not capable of running Kata Containers
```

**Comment by ssst0n3** [comment]
https://blog.csdn.net/kunyus/article/details/106986621

https://discuss.linuxcontainers.org/t/lxd-4-0-cannot-use-vm-errors/7312

**Comment by ssst0n3** [comment]
```
# /opt/kata/bin/kata-runtime kata-check
System is capable of running Kata Containers
System can currently create Kata Containers
```

**Comment by ssst0n3** [comment]
```
root@ubuntu:~# docker run --runtime kata-runtime ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
dbf6a9befcde: Pull complete
Digest: sha256:dfd64a3b4296d8c9b62aa3309984f8620b98d87e47492599ee20739e8eb54fbf
Status: Downloaded newer image for ubuntu:latest
docker: Error response from daemon: OCI runtime create failed: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -object memory-backend-ram,id=dimm1,size=2048M: cannot set up guest memory 'dimm1': Cannot allocate memory: unknown.
ERRO[0015] error waiting for container: context canceled
```

**Comment by ssst0n3** [comment]
```
version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:ubuntu-20.04_docker-ce-19.03.11_containerd.io-1.4.9_runc-1.0.1
    ports:
      - "2222:22"
    command: /start_vm.sh -m 4096M -cpu host -enable-kvm
    devices:
      - "/dev/kvm:/dev/kvm"
```
